=== beastthegreat/core-java/first/bin/A1.dtd
<!ELEMENT emails (note+)>
<!ELEMENT note (to+,from,date,subject,contents)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT contents (attachments?,msg)>
<!ELEMENT attachments (file+)>
<!ELEMENT msg (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ATTLIST note spam (yes|no) "no" important CDATA #REQUIRED>
<!ENTITY IACSD "Institute of Advanced Computing and Software Development">

=== beastthegreat/core-java/first/bin/a1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE emails SYSTEM "A1.dtd">
<emails>
   <note spam="no" important="aa">
      <to>abc@gmail.com</to>
      <to>xyz@gmail.com</to>
      <to>pqr@gmail.com</to>
      <from>kkk@gmail.com</from>
      <date>22/10/2018</date>
      <subject>This is subject</subject>
      <contents>
         <attachments>
              <file>abc</file>
              <file>pqr</file>
         </attachments>
         <msg>
            This is message
            as jshdkj kjhkjhdkjh
             ahsdkjhskjhf
         </msg>   
      </contents>
   </note>
   <note spam="no" important="aa">
      <to>abc@gmail.com</to>
      <to>xyz@gmail.com</to>
      <to>pqr@gmail.com</to>
      <from>kkk@gmail.com</from>
      <date>22/10/2018</date>
      <subject>This is subject</subject>
      <contents>
         <attachments>
              <file>abc</file>
              <file>pqr</file>
         </attachments>
         <msg>
            This is message
            as jshdkj kjhkjhdkjh
             ahsdkjhskjhf
         </msg>   
      </contents>
   </note>
</emails>
